### ISSUE TITLE
Investigate generation of documentation

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-python#30]
Investigate current possibilities for documentation generation in pyo3 and pyo3-pack. Ideally, we'd generate something similar to readthedocs. This is the last item from #5.

**Comment by RealNicolasBourbaki** [comment]
I have tried a few things, and it seems Sphinx is a very nice option.
we can use `automodule` and `autoclass` to build doc base on docstrings in rust.
here is an example project: https://fastobo.readthedocs.io/en/latest/
and the code is here: https://github.com/fastobo/fastobo-py/tree/master/docs

another option is generate `json` file based on rust docstrings, and use `Sphinx` to generate documentation. But it seems a bit unnecessary since `automodule` and `autoclass` can already handle docstrings very well.

The style is also Read the Docs.

**Comment by danieldk** [comment]
Closing this issue, as it applied to the Rust version of the module.
