### ISSUE TITLE
Download pyo3-pack instead of cargo install

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-python#65]
Downloading a precompiled version of pyo3-pack would shave off more than 10 minutes from build times. Any objections to this?

Although it seems like something is messed up for the 0.6.1 binary, at least it's not possible for me to run it locally or on CI. Bash just states, that the file or directory doesn't exist. The newest release works just fine locally.

**Comment by danieldk** [comment]
> Although it seems like something is messed up for the 0.6.1 binary, at least it's not possible for me to run it locally or on CI. Bash just states, that the file or directory doesn't exist. The newest release works just fine locally.

Probably because the interpreter path is wrong:

```
❯ readelf --headers pyo3-pack | grep interpret
      [Requesting program interpreter: /lib/ld64.so.1]
```

Oddly enough it also wants to link to dbus!:

```
❯ readelf -d pyo3-pack | grep Shared
 0x0000000000000001 (NEEDED)             Shared library: [libdbus-1.so.3]
```

I don't know, some weird things seem to happen in these builds. I am move in favor of axing `pyo3-pack`. On Linux it works perfectly fine without, on macOS you need some extra configuration flag. I'll do a PR.

**Comment by sebpuetz** [comment]
#67
